### ISSUE TITLE
Create python script for applying watershed technique

### ISSUE THREAD

**Issue by TerenceTYAranowitz** [UC-Irvine-CS175/final-project-e-mcheese-2#3]
#### Description
Modify augmentations.py so that we have an augmentation that applies the watershed technique to the images. It will return a tuple of the mask of the images as well the number of focci detected.

NOTE: Watershed augmentation must be the last augmentation to be called as it will return a tuple instead of just the image itself so it will not fit as a input to other augmentations which only expect the image and not a tuple.

#### Files
augmentation.py

#### Tasks
- [ ] Create new ApplyWatershed class in augmentations.py
- [ ] Create a __call__ function for augmentations.py and apply watershed to the image get the number of focci and also return the masked image for later

**Comment by JarrodRShepherd** [comment]
Sounds good, let's start working on it!
